#
# Intel(R) 64 and IA-32 Architectures Software DeveloperÅfs Manual
# Order Number: 325462-046US
# March 2013
#

#
# 18.7
# PERFORMANCE MONITORING FOR PROCESSORS BASED ON
# INTEL(R) MICROARCHITECTURE CODE NAME WESTMERE
#
